In [2]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('customer.csv')

In [5]:

df.sample(5)

age  gender   review education purchased
36   34  Female     Good        UG       Yes
6    18    Male     Good    School        No
22   18  Female     Poor        PG       Yes
38   45  Female     Good    School        No
34   86    Male  Average    School        No

In [6]:
df=df.iloc[:,2:]

In [8]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],
                                              df.iloc[:,-1],test_size=0.2)

x_train

review education
11     Good        UG
46     Poor        PG
21  Average        PG
44  Average        UG
9      Good        UG
16     Poor        UG
34  Average    School
13  Average    School
28     Poor    School
41     Good        PG
25     Good    School
26     Poor        PG
0   Average    School
17     Poor        UG
40     Good    School
47     Good        PG
38     Good    School
31     Poor    School
30  Average        UG
24  Average        PG
14     Poor        PG
15     Poor        UG
35     Poor    School
5   Average    School
45     Poor        PG
19     Poor        PG
2      Good        PG
10     Good        UG
43     Poor        PG
22     Poor        PG
42     Good        PG
20  Average    School
48     Good        UG
7      Poor    School
37  Average        PG
3      Good        PG
33     Good        PG
8   Average        UG
18     Good    School
39     Poor        PG

In [14]:
x_test

review education
29  Average        UG
6      Good    School
27     Poor        PG
4   Average        UG
32  Average        UG
12     Poor    School
36     Good        UG
49     Good        UG
1      Poor        UG
23     Good    School

In [15]:
y_train

11    Yes
46     No
21     No
44     No
9     Yes
16    Yes
34     No
13     No
28     No
41    Yes
25     No
26     No
0      No
17    Yes
40     No
47    Yes
38     No
31    Yes
30     No
24    Yes
14    Yes
15     No
35    Yes
5     Yes
45    Yes
19    Yes
2      No
10    Yes
43     No
22    Yes
42    Yes
20    Yes
48    Yes
7     Yes
37    Yes
3      No
33    Yes
8      No
18     No
39     No
Name: purchased, dtype: object

In [16]:
x_train.shape,x_test.shape

((40, 2), (10, 2))

In [17]:
df.shape

(50, 3)

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [19]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [21]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [23]:
x_train=oe.transform(x_train)

In [24]:
x_train

array([[2., 1.],
       [0., 2.],
       [1., 2.],
       [1., 1.],
       [2., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.]])

In [26]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [27]:
x_train

array([[2., 1.],
       [0., 2.],
       [1., 2.],
       [1., 1.],
       [2., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.]])

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
le=LabelEncoder()

In [30]:
le.fit(y_train)

LabelEncoder()

In [31]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [32]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [33]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])